### ISSUE TITLE
error, help thks

### ISSUE THREAD

**Issue by wjsunday** [wego/kong-jwt-claim-headers#3]
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:56
nginx: [warn] [lua] init.lua:459: init(): database has pending migrations:
          core: 005_120_to_130, 008_150_to_200, 009_200_to_210
     hmac-auth: 003_200_to_210
        oauth2: 004_200_to_210
ip-restriction: 001_200_to_210
           jwt: 003_200_to_210
    basic-auth: 003_200_to_210
      key-auth: 003_200_to_210
           acl: 003_200_to_210
 bot-detection: 001_200_to_210
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:625: error loading module 'kong.plugins.jwt-claim-headers.handler':
...share/lua/5.1/kong/plugins/jwt-claim-headers/handler.lua:2: module 'kong.tools.responses' not found:No LuaRocks module found for kong.tools.responses
	no field package.preload['kong.tools.responses']
	no file './kong/tools/responses.lua'
	no file './kong/tools/responses/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses/init.ljbc'
	no file '/usr/local/openresty/lualib/kong/tools/responses.ljbc'
	no file '/usr/local/openresty/lualib/kong/tools/responses/init.ljbc'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses.lua'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses/init.lua'
	no file '/usr/local/openresty/lualib/kong/tools/responses.lua'
	no file '/usr/local/openresty/lualib/kong/tools/responses/init.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/kong/tools/responses.lua'
	no file '/usr/local/share/lua/5.1/kong/tools/responses.lua'
	no file '/usr/local/share/lua/5.1/kong/tools/responses/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/tools/responses.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/kong/tools/responses/init.lua'
	no file '/root/.luarocks/share/lua/5.1/kong/tools/responses.lua'
	no file '/root/.luarocks/share/lua/5.1/kong/tools/responses/init.lua'
	no file '/usr/local/openresty/site/lualib/kong/tools/responses.so'
	no file '/usr/local/openresty/lualib/kong/tools/responses.so'
	no file './kong/tools/responses.so'
	no file '/usr/local/lib/lua/5.1/kong/tools/responses.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong/tools/responses.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/root/.luarocks/lib/lua/5.1/kong/tools/responses.so'
	no file '/usr/local/openresty/site/lualib/kong.so'
	no file '/usr/local/openresty/lualib/kong.so'
	no file './kong.so'
	no file '/usr/local/lib/lua/5.1/kong.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/kong.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/root/.luarocks/lib/lua/5.1/kong.so'
stack traceback:
	[C]: in function 'require'
	...share/lua/5.1/kong/plugins/jwt-claim-headers/handler.lua:2: in main chunk
	[C]: at 0x7f3fc7a637a0
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:616: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:485: in function 'init'
	init_by_lua:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:625: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:485: in function 'init'
	init_by_lua:3: in main chunk

  Run with --v (verbose) or --vv (debug) for more details

**Comment by Jqnxyz** [comment]
> nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:625: error loading module 'kong.plugins.jwt-claim-headers.handler': ...share/lua/5.1/kong/plugins/jwt-claim-headers/handler.lua:2: module 'kong.tools.responses' not found:No LuaRocks module found for kong.tools.responses

Kong *1.0.0* released in *2018-12-18* fully removed a few modules, including `kong.tools.responses` as your attached log states was unable to find. 

See the [official Kong changelog for 1.0.0](https://github.com/Kong/kong/blob/master/CHANGELOG.md#user-content-plugins-24:~:text=kong.tools.responses%20module%20was), the package needs to be updated to migrate to using the [Kong Plugin Development Kit](https://docs.konghq.com/2.1.x/pdk/).

**Comment by Jqnxyz** [comment]
@danielpoonwj has a pull request waiting that fixes this issue, while you wait for the merge you could instead pull from the [kong-2.0-compat branch](https://github.com/wego/kong-jwt-claim-headers/tree/kong-2.0-compat) directly instead of waiting for the merge to master.

**Comment by Jqnxyz** [comment]
Fixed in #2

**Comment by danielpoonwj** [comment]
hi @wjsunday thanks for raising this issue! i've merged the fix into master
